//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScottLane.DataTidy.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScottLane.DataTidy.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        public static string BatchContinuteOnErrorCategory {
            get {
                return ResourceManager.GetString("BatchContinuteOnErrorCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If True, will execute subsequent operations if an error occurs..
        /// </summary>
        public static string BatchContinuteOnErrorDescription {
            get {
                return ResourceManager.GetString("BatchContinuteOnErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue On Error.
        /// </summary>
        public static string BatchContinuteOnErrorDisplayName {
            get {
                return ResourceManager.GetString("BatchContinuteOnErrorDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (Copy).
        /// </summary>
        public static string BatchCopy {
            get {
                return ResourceManager.GetString("BatchCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully executed {0}.
        /// </summary>
        public static string BatchExecuted {
            get {
                return ResourceManager.GetString("BatchExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing {0}.
        /// </summary>
        public static string BatchExecuting {
            get {
                return ResourceManager.GetString("BatchExecuting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string BatchIDCategory {
            get {
                return ResourceManager.GetString("BatchIDCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The unique batch identifier..
        /// </summary>
        public static string BatchIDDescription {
            get {
                return ResourceManager.GetString("BatchIDDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string BatchIDDisplayName {
            get {
                return ResourceManager.GetString("BatchIDDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string BatchNameCategory {
            get {
                return ResourceManager.GetString("BatchNameCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The batch name..
        /// </summary>
        public static string BatchNameDescription {
            get {
                return ResourceManager.GetString("BatchNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string BatchNameDisplayName {
            get {
                return ResourceManager.GetString("BatchNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string BatchOperationCountCategory {
            get {
                return ResourceManager.GetString("BatchOperationCountCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of enabled operations in the batch..
        /// </summary>
        public static string BatchOperationCountDescription {
            get {
                return ResourceManager.GetString("BatchOperationCountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations.
        /// </summary>
        public static string BatchOperationCountDisplayName {
            get {
                return ResourceManager.GetString("BatchOperationCountDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no enabled operations in the batch.
        /// </summary>
        public static string BatchValidateNoOperations {
            get {
                return ResourceManager.GetString("BatchValidateNoOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ComparisonDataSource {
            get {
                object obj = ResourceManager.GetObject("ComparisonDataSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsComparison.
        /// </summary>
        public static string ComparisonDataSourceColumnNameComparison {
            get {
                return ResourceManager.GetString("ComparisonDataSourceColumnNameComparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Differences.
        /// </summary>
        public static string ComparisonDataSourceColumnNameDifferences {
            get {
                return ResourceManager.GetString("ComparisonDataSourceColumnNameDifferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string ComparisonDataSourceColumnNameResult {
            get {
                return ResourceManager.GetString("ComparisonDataSourceColumnNameResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsSource.
        /// </summary>
        public static string ComparisonDataSourceColumnNameSource {
            get {
                return ResourceManager.GetString("ComparisonDataSourceColumnNameSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparing data.
        /// </summary>
        public static string ComparisonDataSourceComparingData {
            get {
                return ResourceManager.GetString("ComparisonDataSourceComparingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparison.
        /// </summary>
        public static string ComparisonDataSourceComparisonDataCategory {
            get {
                return ResourceManager.GetString("ComparisonDataSourceComparisonDataCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data source to compare against..
        /// </summary>
        public static string ComparisonDataSourceComparisonDataDescription {
            get {
                return ResourceManager.GetString("ComparisonDataSourceComparisonDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparison Data.
        /// </summary>
        public static string ComparisonDataSourceComparisonDataDisplayName {
            get {
                return ResourceManager.GetString("ComparisonDataSourceComparisonDataDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compares two data sources and outputs the results.
        /// </summary>
        public static string ComparisonDataSourceDescription {
            get {
                return ResourceManager.GetString("ComparisonDataSourceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare Data Sources.
        /// </summary>
        public static string ComparisonDataSourceDisplayName {
            get {
                return ResourceManager.GetString("ComparisonDataSourceDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparison.
        /// </summary>
        public static string ComparisonDataSourceFieldMappingsCategory {
            get {
                return ResourceManager.GetString("ComparisonDataSourceFieldMappingsCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mappings between data source Fields to compare..
        /// </summary>
        public static string ComparisonDataSourceFieldMappingsDescription {
            get {
                return ResourceManager.GetString("ComparisonDataSourceFieldMappingsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Mappings.
        /// </summary>
        public static string ComparisonDataSourceFieldMappingsDisplayName {
            get {
                return ResourceManager.GetString("ComparisonDataSourceFieldMappingsDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare {0} with {1}.
        /// </summary>
        public static string ComparisonDataSourceFriendlyName {
            get {
                return ResourceManager.GetString("ComparisonDataSourceFriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Comparison Data Source&gt;.
        /// </summary>
        public static string ComparisonDataSourceFriendlyNameComparisonData {
            get {
                return ResourceManager.GetString("ComparisonDataSourceFriendlyNameComparisonData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Source Data&gt;.
        /// </summary>
        public static string ComparisonDataSourceFriendlyNameSourceData {
            get {
                return ResourceManager.GetString("ComparisonDataSourceFriendlyNameSourceData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparison.
        /// </summary>
        public static string ComparisonDataSourceKeyMappingsCategory {
            get {
                return ResourceManager.GetString("ComparisonDataSourceKeyMappingsCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mappings between data source primary keys..
        /// </summary>
        public static string ComparisonDataSourceKeyMappingsDescription {
            get {
                return ResourceManager.GetString("ComparisonDataSourceKeyMappingsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Mappings.
        /// </summary>
        public static string ComparisonDataSourceKeyMappingsDisplayName {
            get {
                return ResourceManager.GetString("ComparisonDataSourceKeyMappingsDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparison.
        /// </summary>
        public static string ComparisonDataSourceOutputCategory {
            get {
                return ResourceManager.GetString("ComparisonDataSourceOutputCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The comparison results to output..
        /// </summary>
        public static string ComparisonDataSourceOutputDescription {
            get {
                return ResourceManager.GetString("ComparisonDataSourceOutputDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string ComparisonDataSourceOutputDisplayName {
            get {
                return ResourceManager.GetString("ComparisonDataSourceOutputDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparison.
        /// </summary>
        public static string ComparisonDataSourceSourceDataCategory {
            get {
                return ResourceManager.GetString("ComparisonDataSourceSourceDataCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data source to compare..
        /// </summary>
        public static string ComparisonDataSourceSourceDataDescription {
            get {
                return ResourceManager.GetString("ComparisonDataSourceSourceDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Data.
        /// </summary>
        public static string ComparisonDataSourceSourceDataDisplayName {
            get {
                return ResourceManager.GetString("ComparisonDataSourceSourceDataDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Comparison Data Source.
        /// </summary>
        public static string ComparisonDataSourceValidateComparisonData {
            get {
                return ResourceManager.GetString("ComparisonDataSourceValidateComparisonData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add at least one Key Mapping.
        /// </summary>
        public static string ComparisonDataSourceValidateKeyMappings {
            get {
                return ResourceManager.GetString("ComparisonDataSourceValidateKeyMappings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Source Data Source.
        /// </summary>
        public static string ComparisonDataSourceValidateSourceData {
            get {
                return ResourceManager.GetString("ComparisonDataSourceValidateSourceData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ConnectionAttribute ResourceName {0} does not exist in the Assembly. Ensure that the resource name is correct and the resource&apos;s build action is &apos;Embedded Resource&apos;..
        /// </summary>
        public static string ConnectionAttributeResourceNotFound {
            get {
                return ResourceManager.GetString("ConnectionAttributeResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Project has not been specified.
        /// </summary>
        public static string ConnectionValidateParentProject {
            get {
                return ResourceManager.GetString("ConnectionValidateParentProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DataSourceAttribute ResourceName {0} does not exist in the Assembly. Ensure that the resource name is correct and the resource&apos;s build action is &apos;Embedded Resource&apos;..
        /// </summary>
        public static string DataSourceAttributeResourceNotFound {
            get {
                return ResourceManager.GetString("DataSourceAttributeResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (Copy).
        /// </summary>
        public static string DataSourceCloneSuffix {
            get {
                return ResourceManager.GetString("DataSourceCloneSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source.
        /// </summary>
        public static string DataSourceFriendlyName {
            get {
                return ResourceManager.GetString("DataSourceFriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string DataSourceIDCategory {
            get {
                return ResourceManager.GetString("DataSourceIDCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The unique data source identifier..
        /// </summary>
        public static string DataSourceIDDescription {
            get {
                return ResourceManager.GetString("DataSourceIDDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string DataSourceIDDisplayName {
            get {
                return ResourceManager.GetString("DataSourceIDDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string DataSourceNameCategory {
            get {
                return ResourceManager.GetString("DataSourceNameCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data source name..
        /// </summary>
        public static string DataSourceNameDescription {
            get {
                return ResourceManager.GetString("DataSourceNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string DataSourceNameDisplayName {
            get {
                return ResourceManager.GetString("DataSourceNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Data Source Connection has not been specified.
        /// </summary>
        public static string DataSourceValidateParentConnection {
            get {
                return ResourceManager.GetString("DataSourceValidateParentConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DuplicateDataSource {
            get {
                object obj = ResourceManager.GetObject("DuplicateDataSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicates.
        /// </summary>
        public static string DuplicateDataSourceDataSourceCategory {
            get {
                return ResourceManager.GetString("DuplicateDataSourceDataSourceCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data source to find duplicates in..
        /// </summary>
        public static string DuplicateDataSourceDataSourceDescription {
            get {
                return ResourceManager.GetString("DuplicateDataSourceDataSourceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source.
        /// </summary>
        public static string DuplicateDataSourceDataSourceDisplayName {
            get {
                return ResourceManager.GetString("DuplicateDataSourceDataSourceDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finds duplicate records in a data source.
        /// </summary>
        public static string DuplicateDataSourceDescription {
            get {
                return ResourceManager.GetString("DuplicateDataSourceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Duplicate Records.
        /// </summary>
        public static string DuplicateDataSourceDisplayName {
            get {
                return ResourceManager.GetString("DuplicateDataSourceDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find duplicates in {0}.
        /// </summary>
        public static string DuplicateDataSourceFriendlyName {
            get {
                return ResourceManager.GetString("DuplicateDataSourceFriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Data Source&gt;.
        /// </summary>
        public static string DuplicateDataSourceFriendlyNameDataSource {
            get {
                return ResourceManager.GetString("DuplicateDataSourceFriendlyNameDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicates.
        /// </summary>
        public static string DuplicateDataSourceKeyFieldsCategory {
            get {
                return ResourceManager.GetString("DuplicateDataSourceKeyFieldsCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fields that should be unique in the data source..
        /// </summary>
        public static string DuplicateDataSourceKeyFieldsDescription {
            get {
                return ResourceManager.GetString("DuplicateDataSourceKeyFieldsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Fields.
        /// </summary>
        public static string DuplicateDataSourceKeyFieldsDisplayName {
            get {
                return ResourceManager.GetString("DuplicateDataSourceKeyFieldsDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Data Source.
        /// </summary>
        public static string DuplicateDataSourceValidateDataSource {
            get {
                return ResourceManager.GetString("DuplicateDataSourceValidateDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one Key Field.
        /// </summary>
        public static string DuplicateDataSourceValidateKeyFields {
            get {
                return ResourceManager.GetString("DuplicateDataSourceValidateKeyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string FieldValueDestinationFieldCategory {
            get {
                return ResourceManager.GetString("FieldValueDestinationFieldCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The destination field to store the value in..
        /// </summary>
        public static string FieldValueDestinationFieldDescription {
            get {
                return ResourceManager.GetString("FieldValueDestinationFieldDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination Field.
        /// </summary>
        public static string FieldValueDestinationFieldDisplayName {
            get {
                return ResourceManager.GetString("FieldValueDestinationFieldDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FilterDataSource {
            get {
                object obj = ResourceManager.GetObject("FilterDataSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string FilterDataSourceDataSourceCategory {
            get {
                return ResourceManager.GetString("FilterDataSourceDataSourceCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data source to filter..
        /// </summary>
        public static string FilterDataSourceDataSourceDescription {
            get {
                return ResourceManager.GetString("FilterDataSourceDataSourceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source.
        /// </summary>
        public static string FilterDataSourceDataSourceDisplayName {
            get {
                return ResourceManager.GetString("FilterDataSourceDataSourceDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters a data source.
        /// </summary>
        public static string FilterDataSourceDescription {
            get {
                return ResourceManager.GetString("FilterDataSourceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter a Data Source.
        /// </summary>
        public static string FilterDataSourceDisplayName {
            get {
                return ResourceManager.GetString("FilterDataSourceDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string FilterDataSourceFiltersCategory {
            get {
                return ResourceManager.GetString("FilterDataSourceFiltersCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The filters to apply to the data source..
        /// </summary>
        public static string FilterDataSourceFiltersDescription {
            get {
                return ResourceManager.GetString("FilterDataSourceFiltersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string FilterDataSourceFiltersDisplayName {
            get {
                return ResourceManager.GetString("FilterDataSourceFiltersDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter {0} by {1}.
        /// </summary>
        public static string FilterDataSourceFriendlyName {
            get {
                return ResourceManager.GetString("FilterDataSourceFriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The OperationAttribute ResourceName {0} does not exist in the Assembly. Ensure that the resource name is correct and the resource&apos;s build action is &apos;Embedded Resource&apos;..
        /// </summary>
        public static string OperationAttributeResourceNotFound {
            get {
                return ResourceManager.GetString("OperationAttributeResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Project.
        /// </summary>
        public static string ProjectDefaultName {
            get {
                return ResourceManager.GetString("ProjectDefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .json.
        /// </summary>
        public static string ProjectFileExtension {
            get {
                return ResourceManager.GetString("ProjectFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap UtilityConnection {
            get {
                object obj = ResourceManager.GetObject("UtilityConnection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utility data sources.
        /// </summary>
        public static string UtilityConnectionDescription {
            get {
                return ResourceManager.GetString("UtilityConnectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilities.
        /// </summary>
        public static string UtilityConnectionDisplayName {
            get {
                return ResourceManager.GetString("UtilityConnectionDisplayName", resourceCulture);
            }
        }
    }
}
