//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScottLane.DataTidy.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScottLane.DataTidy.Core.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ComparisonDataSource {
            get {
                object obj = ResourceManager.GetObject("ComparisonDataSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ConnectionAttribute ResourceName {0} does not exist in the Assembly. Ensure that the resource name is correct and the resource&apos;s build action is &apos;Embedded Resource&apos;..
        /// </summary>
        internal static string ConnectionAttributeResourceNotFound {
            get {
                return ResourceManager.GetString("ConnectionAttributeResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DataSourceAttribute ResourceName {0} does not exist in the Assembly. Ensure that the resource name is correct and the resource&apos;s build action is &apos;Embedded Resource&apos;..
        /// </summary>
        internal static string DataSourceAttributeResourceNotFound {
            get {
                return ResourceManager.GetString("DataSourceAttributeResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DuplicateDataSource {
            get {
                object obj = ResourceManager.GetObject("DuplicateDataSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string FieldValueDestinationFieldCategory {
            get {
                return ResourceManager.GetString("FieldValueDestinationFieldCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The destination field to store the value in..
        /// </summary>
        internal static string FieldValueDestinationFieldDescription {
            get {
                return ResourceManager.GetString("FieldValueDestinationFieldDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination Field.
        /// </summary>
        internal static string FieldValueDestinationFieldDisplayName {
            get {
                return ResourceManager.GetString("FieldValueDestinationFieldDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The OperationAttribute ResourceName {0} does not exist in the Assembly. Ensure that the resource name is correct and the resource&apos;s build action is &apos;Embedded Resource&apos;..
        /// </summary>
        internal static string OperationAttributeResourceNotFound {
            get {
                return ResourceManager.GetString("OperationAttributeResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string ProjectDefaultName {
            get {
                return ResourceManager.GetString("ProjectDefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .json.
        /// </summary>
        internal static string ProjectFileExtension {
            get {
                return ResourceManager.GetString("ProjectFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UtilityConnection {
            get {
                object obj = ResourceManager.GetObject("UtilityConnection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
