//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScottLane.DataTidy.File.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScottLane.DataTidy.File.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CsvDataSource {
            get {
                object obj = ResourceManager.GetObject("CsvDataSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV File.
        /// </summary>
        internal static string CsvDataSourceDelimiterCategory {
            get {
                return ResourceManager.GetString("CsvDataSourceDelimiterCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The delimiter used to separate fields in the file..
        /// </summary>
        internal static string CsvDataSourceDelimiterDescription {
            get {
                return ResourceManager.GetString("CsvDataSourceDelimiterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delimiter.
        /// </summary>
        internal static string CsvDataSourceDelimiterDisplayName {
            get {
                return ResourceManager.GetString("CsvDataSourceDelimiterDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reads records from a comma-separated value file.
        /// </summary>
        internal static string CsvDataSourceDescription {
            get {
                return ResourceManager.GetString("CsvDataSourceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV File.
        /// </summary>
        internal static string CsvDataSourceDisplayName {
            get {
                return ResourceManager.GetString("CsvDataSourceDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting data from {0}.
        /// </summary>
        internal static string CsvDataSourceExtract {
            get {
                return ResourceManager.GetString("CsvDataSourceExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV File.
        /// </summary>
        internal static string CsvDataSourceFriendlyName {
            get {
                return ResourceManager.GetString("CsvDataSourceFriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV File.
        /// </summary>
        internal static string CsvDataSourceMissingValuesCategory {
            get {
                return ResourceManager.GetString("CsvDataSourceMissingValuesCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines how missing values in the input file are interpreted..
        /// </summary>
        internal static string CsvDataSourceMissingValuesDescription {
            get {
                return ResourceManager.GetString("CsvDataSourceMissingValuesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Values.
        /// </summary>
        internal static string CsvDataSourceMissingValuesDisplayName {
            get {
                return ResourceManager.GetString("CsvDataSourceMissingValuesDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV File.
        /// </summary>
        internal static string CsvDataSourcePathCategory {
            get {
                return ResourceManager.GetString("CsvDataSourcePathCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The comma-separated value file path..
        /// </summary>
        internal static string CsvDataSourcePathDescription {
            get {
                return ResourceManager.GetString("CsvDataSourcePathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string CsvDataSourcePathDisplayName {
            get {
                return ResourceManager.GetString("CsvDataSourcePathDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a Delimiter.
        /// </summary>
        internal static string CsvDataSourceValidateDelimiter {
            get {
                return ResourceManager.GetString("CsvDataSourceValidateDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CsvFileCreateOperation {
            get {
                object obj = ResourceManager.GetObject("CsvFileCreateOperation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating {0}.
        /// </summary>
        internal static string CsvFileCreateOperationCreating {
            get {
                return ResourceManager.GetString("CsvFileCreateOperationCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV File.
        /// </summary>
        internal static string CsvFileCreateOperationDataSourceCategory {
            get {
                return ResourceManager.GetString("CsvFileCreateOperationDataSourceCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data source to read records from..
        /// </summary>
        internal static string CsvFileCreateOperationDataSourceDescription {
            get {
                return ResourceManager.GetString("CsvFileCreateOperationDataSourceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source.
        /// </summary>
        internal static string CsvFileCreateOperationDataSourceDisplayName {
            get {
                return ResourceManager.GetString("CsvFileCreateOperationDataSourceDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV File.
        /// </summary>
        internal static string CsvFileCreateOperationDelimiterCategory {
            get {
                return ResourceManager.GetString("CsvFileCreateOperationDelimiterCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The delimiter used to separate fields in the file..
        /// </summary>
        internal static string CsvFileCreateOperationDelimiterDescription {
            get {
                return ResourceManager.GetString("CsvFileCreateOperationDelimiterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delimiter.
        /// </summary>
        internal static string CsvFileCreateOperationDelimiterDisplayName {
            get {
                return ResourceManager.GetString("CsvFileCreateOperationDelimiterDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a Comma-Separated Value File.
        /// </summary>
        internal static string CsvFileCreateOperationDescription {
            get {
                return ResourceManager.GetString("CsvFileCreateOperationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create CSV File.
        /// </summary>
        internal static string CsvFileCreateOperationDisplayName {
            get {
                return ResourceManager.GetString("CsvFileCreateOperationDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV File.
        /// </summary>
        internal static string CsvFileCreateOperationExcelLeadingZeroesCategory {
            get {
                return ResourceManager.GetString("CsvFileCreateOperationExcelLeadingZeroesCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If True, will output numeric fields in a format that will preserve leading zeroes when opened in Microsoft Excel..
        /// </summary>
        internal static string CsvFileCreateOperationExcelLeadingZeroesDescription {
            get {
                return ResourceManager.GetString("CsvFileCreateOperationExcelLeadingZeroesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Leading Zeroes.
        /// </summary>
        internal static string CsvFileCreateOperationExcelLeadingZeroesDisplayName {
            get {
                return ResourceManager.GetString("CsvFileCreateOperationExcelLeadingZeroesDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing {0}.
        /// </summary>
        internal static string CsvFileCreateOperationExecute {
            get {
                return ResourceManager.GetString("CsvFileCreateOperationExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating {0}.
        /// </summary>
        internal static string CsvFileCreateOperationExecuteCreating {
            get {
                return ResourceManager.GetString("CsvFileCreateOperationExecuteCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully created {0}.
        /// </summary>
        internal static string CsvFileCreateOperationExecuteSuccessful {
            get {
                return ResourceManager.GetString("CsvFileCreateOperationExecuteSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create records in {0} from {1}.
        /// </summary>
        internal static string CsvFileCreateOperationFriendlyName {
            get {
                return ResourceManager.GetString("CsvFileCreateOperationFriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Data Source&gt;.
        /// </summary>
        internal static string CsvFileCreateOperationFriendlyNameDataSource {
            get {
                return ResourceManager.GetString("CsvFileCreateOperationFriendlyNameDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Path&gt;.
        /// </summary>
        internal static string CsvFileCreateOperationFriendlyNamePath {
            get {
                return ResourceManager.GetString("CsvFileCreateOperationFriendlyNamePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV File.
        /// </summary>
        internal static string CsvFileCreateOperationOutputPathCategory {
            get {
                return ResourceManager.GetString("CsvFileCreateOperationOutputPathCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output file path..
        /// </summary>
        internal static string CsvFileCreateOperationOutputPathDescription {
            get {
                return ResourceManager.GetString("CsvFileCreateOperationOutputPathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Path.
        /// </summary>
        internal static string CsvFileCreateOperationOutputPathDisplayName {
            get {
                return ResourceManager.GetString("CsvFileCreateOperationOutputPathDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a Delimiter.
        /// </summary>
        internal static string CsvFileCreateOperationValidateDelimiter {
            get {
                return ResourceManager.GetString("CsvFileCreateOperationValidateDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ExcelDataSource {
            get {
                object obj = ResourceManager.GetObject("ExcelDataSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provides data from a Microsoft Excel workbook.
        /// </summary>
        internal static string ExcelDataSourceDescription {
            get {
                return ResourceManager.GetString("ExcelDataSourceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Excel File.
        /// </summary>
        internal static string ExcelDataSourceDisplayName {
            get {
                return ResourceManager.GetString("ExcelDataSourceDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting data from {0}.
        /// </summary>
        internal static string ExcelDataSourceExtract {
            get {
                return ResourceManager.GetString("ExcelDataSourceExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Excel File.
        /// </summary>
        internal static string ExcelDataSourceFirstRowHeadersCategory {
            get {
                return ResourceManager.GetString("ExcelDataSourceFirstRowHeadersCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If True, will treat the first row as headers..
        /// </summary>
        internal static string ExcelDataSourceFirstRowHeadersDescription {
            get {
                return ResourceManager.GetString("ExcelDataSourceFirstRowHeadersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Row Headers.
        /// </summary>
        internal static string ExcelDataSourceFirstRowHeadersDisplayName {
            get {
                return ResourceManager.GetString("ExcelDataSourceFirstRowHeadersDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Excel File.
        /// </summary>
        internal static string ExcelDataSourceFriendlyName {
            get {
                return ResourceManager.GetString("ExcelDataSourceFriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Excel File.
        /// </summary>
        internal static string ExcelDataSourcePathCategory {
            get {
                return ResourceManager.GetString("ExcelDataSourcePathCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Microsoft Excel file path..
        /// </summary>
        internal static string ExcelDataSourcePathDescription {
            get {
                return ResourceManager.GetString("ExcelDataSourcePathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string ExcelDataSourcePathDisplayName {
            get {
                return ResourceManager.GetString("ExcelDataSourcePathDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Excel File.
        /// </summary>
        internal static string ExcelDataSourceSheetNameCategory {
            get {
                return ResourceManager.GetString("ExcelDataSourceSheetNameCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The worksheet to read records from..
        /// </summary>
        internal static string ExcelDataSourceSheetNameDescription {
            get {
                return ResourceManager.GetString("ExcelDataSourceSheetNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet Name.
        /// </summary>
        internal static string ExcelDataSourceSheetNameDisplayName {
            get {
                return ResourceManager.GetString("ExcelDataSourceSheetNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified file is not a Microsoft Excel file..
        /// </summary>
        internal static string ExcelDataSourceValidateFileExtension {
            get {
                return ResourceManager.GetString("ExcelDataSourceValidateFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the Sheet Name.
        /// </summary>
        internal static string ExcelDataSourceValidateSheetName {
            get {
                return ResourceManager.GetString("ExcelDataSourceValidateSheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string FileDataSourcePathCategory {
            get {
                return ResourceManager.GetString("FileDataSourcePathCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file path..
        /// </summary>
        internal static string FileDataSourcePathDescription {
            get {
                return ResourceManager.GetString("FileDataSourcePathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string FileDataSourcePathDisplayName {
            get {
                return ResourceManager.GetString("FileDataSourcePathDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify the file Path..
        /// </summary>
        internal static string FileDataSourceValidatePathMissing {
            get {
                return ResourceManager.GetString("FileDataSourceValidatePathMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string FileOperationDataSourceCategory {
            get {
                return ResourceManager.GetString("FileOperationDataSourceCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data source to read records from..
        /// </summary>
        internal static string FileOperationDataSourceDescription {
            get {
                return ResourceManager.GetString("FileOperationDataSourceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source.
        /// </summary>
        internal static string FileOperationDataSourceDisplayName {
            get {
                return ResourceManager.GetString("FileOperationDataSourceDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0} could not be found.
        /// </summary>
        internal static string FileOperationOpenFileNotFound {
            get {
                return ResourceManager.GetString("FileOperationOpenFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File.
        /// </summary>
        internal static string FileOperationOpenFileText {
            get {
                return ResourceManager.GetString("FileOperationOpenFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the output file.
        /// </summary>
        internal static string FileOperationOpenFileTooltip {
            get {
                return ResourceManager.GetString("FileOperationOpenFileTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FileOperationOpenFolder {
            get {
                object obj = ResourceManager.GetObject("FileOperationOpenFolder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder {0} could not be found.
        /// </summary>
        internal static string FileOperationOpenFolderNotFound {
            get {
                return ResourceManager.GetString("FileOperationOpenFolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Folder.
        /// </summary>
        internal static string FileOperationOpenFolderText {
            get {
                return ResourceManager.GetString("FileOperationOpenFolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open folder in Windows Explorer.
        /// </summary>
        internal static string FileOperationOpenFolderTooltip {
            get {
                return ResourceManager.GetString("FileOperationOpenFolderTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string FileOperationOutputPathCategory {
            get {
                return ResourceManager.GetString("FileOperationOutputPathCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output file path..
        /// </summary>
        internal static string FileOperationOutputPathDescription {
            get {
                return ResourceManager.GetString("FileOperationOutputPathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Path.
        /// </summary>
        internal static string FileOperationOutputPathDisplayName {
            get {
                return ResourceManager.GetString("FileOperationOutputPathDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Data Source.
        /// </summary>
        internal static string FileOperationValidateDataSource {
            get {
                return ResourceManager.GetString("FileOperationValidateDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify the Output Path.
        /// </summary>
        internal static string FileOperationValidateOutputPath {
            get {
                return ResourceManager.GetString("FileOperationValidateOutputPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FileSystemConnection {
            get {
                object obj = ResourceManager.GetObject("FileSystemConnection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provides connectivity files on the file system.
        /// </summary>
        internal static string FileSystemConnectionDescription {
            get {
                return ResourceManager.GetString("FileSystemConnectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File System.
        /// </summary>
        internal static string FileSystemConnectionDisplayName {
            get {
                return ResourceManager.GetString("FileSystemConnectionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File System.
        /// </summary>
        internal static string FileSystemConnectionFriendlyName {
            get {
                return ResourceManager.GetString("FileSystemConnectionFriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FtpConnection {
            get {
                object obj = ResourceManager.GetObject("FtpConnection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provides connectivity to a FTP or SFTP server.
        /// </summary>
        internal static string FtpConnectionDescription {
            get {
                return ResourceManager.GetString("FtpConnectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Transfer Protocol.
        /// </summary>
        internal static string FtpConnectionDisplayName {
            get {
                return ResourceManager.GetString("FtpConnectionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap JsonFileCreateOperation {
            get {
                object obj = ResourceManager.GetObject("JsonFileCreateOperation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON File.
        /// </summary>
        internal static string JsonFileCreateOperationDataSourceCategory {
            get {
                return ResourceManager.GetString("JsonFileCreateOperationDataSourceCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data source to read records from..
        /// </summary>
        internal static string JsonFileCreateOperationDataSourceDescription {
            get {
                return ResourceManager.GetString("JsonFileCreateOperationDataSourceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source.
        /// </summary>
        internal static string JsonFileCreateOperationDataSourceDisplayName {
            get {
                return ResourceManager.GetString("JsonFileCreateOperationDataSourceDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a JSON file.
        /// </summary>
        internal static string JsonFileCreateOperationDescription {
            get {
                return ResourceManager.GetString("JsonFileCreateOperationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create JSON File.
        /// </summary>
        internal static string JsonFileCreateOperationDisplayName {
            get {
                return ResourceManager.GetString("JsonFileCreateOperationDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing {0}.
        /// </summary>
        internal static string JsonFileCreateOperationExecute {
            get {
                return ResourceManager.GetString("JsonFileCreateOperationExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating {0}.
        /// </summary>
        internal static string JsonFileCreateOperationExecuteCreating {
            get {
                return ResourceManager.GetString("JsonFileCreateOperationExecuteCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully created {0}.
        /// </summary>
        internal static string JsonFileCreateOperationExecuteSuccessful {
            get {
                return ResourceManager.GetString("JsonFileCreateOperationExecuteSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create JSON records in {0} from {1}.
        /// </summary>
        internal static string JsonFileCreateOperationFriendlyName {
            get {
                return ResourceManager.GetString("JsonFileCreateOperationFriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Data Source&gt;.
        /// </summary>
        internal static string JsonFileCreateOperationFriendlyNameDataSource {
            get {
                return ResourceManager.GetString("JsonFileCreateOperationFriendlyNameDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Path&gt;.
        /// </summary>
        internal static string JsonFileCreateOperationFriendlyNamePath {
            get {
                return ResourceManager.GetString("JsonFileCreateOperationFriendlyNamePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON File.
        /// </summary>
        internal static string JsonFileCreateOperationOutputPathCategory {
            get {
                return ResourceManager.GetString("JsonFileCreateOperationOutputPathCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output file path..
        /// </summary>
        internal static string JsonFileCreateOperationOutputPathDescription {
            get {
                return ResourceManager.GetString("JsonFileCreateOperationOutputPathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Path.
        /// </summary>
        internal static string JsonFileCreateOperationOutputPathDisplayName {
            get {
                return ResourceManager.GetString("JsonFileCreateOperationOutputPathDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OpenFile {
            get {
                object obj = ResourceManager.GetObject("OpenFile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap XmlFileCreateOperation {
            get {
                object obj = ResourceManager.GetObject("XmlFileCreateOperation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XMLFile.
        /// </summary>
        internal static string XmlFileCreateOperationDataSourceCategory {
            get {
                return ResourceManager.GetString("XmlFileCreateOperationDataSourceCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data source to read records from..
        /// </summary>
        internal static string XmlFileCreateOperationDataSourceDescription {
            get {
                return ResourceManager.GetString("XmlFileCreateOperationDataSourceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source.
        /// </summary>
        internal static string XmlFileCreateOperationDataSourceDisplayName {
            get {
                return ResourceManager.GetString("XmlFileCreateOperationDataSourceDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates an XML file.
        /// </summary>
        internal static string XmlFileCreateOperationDescription {
            get {
                return ResourceManager.GetString("XmlFileCreateOperationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create XML File.
        /// </summary>
        internal static string XmlFileCreateOperationDisplayName {
            get {
                return ResourceManager.GetString("XmlFileCreateOperationDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing {0}.
        /// </summary>
        internal static string XmlFileCreateOperationExecute {
            get {
                return ResourceManager.GetString("XmlFileCreateOperationExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating {0}.
        /// </summary>
        internal static string XmlFileCreateOperationExecuteCreating {
            get {
                return ResourceManager.GetString("XmlFileCreateOperationExecuteCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully created {0}.
        /// </summary>
        internal static string XmlFileCreateOperationExecuteSuccessful {
            get {
                return ResourceManager.GetString("XmlFileCreateOperationExecuteSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create records in {0} from {1}.
        /// </summary>
        internal static string XmlFileCreateOperationFriendlyName {
            get {
                return ResourceManager.GetString("XmlFileCreateOperationFriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Data Source&gt;.
        /// </summary>
        internal static string XmlFileCreateOperationFriendlyNameDataSource {
            get {
                return ResourceManager.GetString("XmlFileCreateOperationFriendlyNameDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Path&gt;.
        /// </summary>
        internal static string XmlFileCreateOperationFriendlyNamePath {
            get {
                return ResourceManager.GetString("XmlFileCreateOperationFriendlyNamePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XMLFile.
        /// </summary>
        internal static string XmlFileCreateOperationOutputPathCategory {
            get {
                return ResourceManager.GetString("XmlFileCreateOperationOutputPathCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output file path..
        /// </summary>
        internal static string XmlFileCreateOperationOutputPathDescription {
            get {
                return ResourceManager.GetString("XmlFileCreateOperationOutputPathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Path.
        /// </summary>
        internal static string XmlFileCreateOperationOutputPathDisplayName {
            get {
                return ResourceManager.GetString("XmlFileCreateOperationOutputPathDisplayName", resourceCulture);
            }
        }
    }
}
