//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScottLane.DataTidy.Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScottLane.DataTidy.Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AddDataSource {
            get {
                object obj = ResourceManager.GetObject("AddDataSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AddProject {
            get {
                object obj = ResourceManager.GetObject("AddProject", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Copy.
        /// </summary>
        internal static string BatchCopySuffix {
            get {
                return ResourceManager.GetString("BatchCopySuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Browser {
            get {
                object obj = ResourceManager.GetObject("Browser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CheckConnectivity {
            get {
                object obj = ResourceManager.GetObject("CheckConnectivity", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ClearCache {
            get {
                object obj = ResourceManager.GetObject("ClearCache", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ClearNotifications {
            get {
                object obj = ResourceManager.GetObject("ClearNotifications", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CloseProject {
            get {
                object obj = ResourceManager.GetObject("CloseProject", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Connection {
            get {
                object obj = ResourceManager.GetObject("Connection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ConnectionDisable32 {
            get {
                object obj = ResourceManager.GetObject("ConnectionDisable32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ConnectionEnable32 {
            get {
                object obj = ResourceManager.GetObject("ConnectionEnable32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ConnectionsForm16 {
            get {
                object obj = ResourceManager.GetObject("ConnectionsForm16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ConnectionsForm24 {
            get {
                object obj = ResourceManager.GetObject("ConnectionsForm24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Copy {
            get {
                object obj = ResourceManager.GetObject("Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DataSource {
            get {
                object obj = ResourceManager.GetObject("DataSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cache was cleared successfully.
        /// </summary>
        internal static string DataSourceFormCacheClearSucceeded {
            get {
                return ResourceManager.GetString("DataSourceFormCacheClearSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove {0} and all associated data sources?.
        /// </summary>
        internal static string DataSourceFormConnectionRemovePrompt {
            get {
                return ResourceManager.GetString("DataSourceFormConnectionRemovePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Connection Confirmation.
        /// </summary>
        internal static string DataSourceFormConnectionRemoveTitle {
            get {
                return ResourceManager.GetString("DataSourceFormConnectionRemoveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing connectivity to {0}.
        /// </summary>
        internal static string DataSourceFormConnectionTest {
            get {
                return ResourceManager.GetString("DataSourceFormConnectionTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is available.
        /// </summary>
        internal static string DataSourceFormConnectionTestAvailable {
            get {
                return ResourceManager.GetString("DataSourceFormConnectionTestAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} connectivity test failed: {1}.
        /// </summary>
        internal static string DataSourceFormConnectionTestNotAvailable {
            get {
                return ResourceManager.GetString("DataSourceFormConnectionTestNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} connectivity test stopped.
        /// </summary>
        internal static string DataSourceFormConnectionTestStopped {
            get {
                return ResourceManager.GetString("DataSourceFormConnectionTestStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DataTable {
            get {
                object obj = ResourceManager.GetObject("DataTable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon DataTidy16 {
            get {
                object obj = ResourceManager.GetObject("DataTidy16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Default {
            get {
                object obj = ResourceManager.GetObject("Default", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Go {
            get {
                object obj = ResourceManager.GetObject("Go", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Information {
            get {
                object obj = ResourceManager.GetObject("Information", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MainFormAbout {
            get {
                object obj = ResourceManager.GetObject("MainFormAbout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove {0}?.
        /// </summary>
        internal static string MainFormBatchRemovePrompt {
            get {
                return ResourceManager.GetString("MainFormBatchRemovePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Batch Confirmation.
        /// </summary>
        internal static string MainFormBatchRemoveTitle {
            get {
                return ResourceManager.GetString("MainFormBatchRemoveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An operation is currently running. Are you sure you want to exit?.
        /// </summary>
        internal static string MainFormCloseAsyncRunningPrompt {
            get {
                return ResourceManager.GetString("MainFormCloseAsyncRunningPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Warning.
        /// </summary>
        internal static string MainFormCloseAsyncRunningTitle {
            get {
                return ResourceManager.GetString("MainFormCloseAsyncRunningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MainFormDocumentation {
            get {
                object obj = ResourceManager.GetObject("MainFormDocumentation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing {0}.
        /// </summary>
        internal static string MainFormExecute {
            get {
                return ResourceManager.GetString("MainFormExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} execution failed: {1}.
        /// </summary>
        internal static string MainFormExecuteFailed {
            get {
                return ResourceManager.GetString("MainFormExecuteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to execute {0}?.
        /// </summary>
        internal static string MainFormExecutePrompt {
            get {
                return ResourceManager.GetString("MainFormExecutePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop failed: {0}.
        /// </summary>
        internal static string MainFormExecuteStopFailed {
            get {
                return ResourceManager.GetString("MainFormExecuteStopFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped {0} after {1}.
        /// </summary>
        internal static string MainFormExecuteStopped {
            get {
                return ResourceManager.GetString("MainFormExecuteStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping....
        /// </summary>
        internal static string MainFormExecuteStopping {
            get {
                return ResourceManager.GetString("MainFormExecuteStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully executed {0} in {1}.
        /// </summary>
        internal static string MainFormExecuteSucceeded {
            get {
                return ResourceManager.GetString("MainFormExecuteSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute Confirmation.
        /// </summary>
        internal static string MainFormExecuteTitle {
            get {
                return ResourceManager.GetString("MainFormExecuteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following error(s) must be corrected before executing:.
        /// </summary>
        internal static string MainFormExecuteValidationError {
            get {
                return ResourceManager.GetString("MainFormExecuteValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MainFormExit {
            get {
                object obj = ResourceManager.GetObject("MainFormExit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MainFormFile {
            get {
                object obj = ResourceManager.GetObject("MainFormFile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MainFormHelp {
            get {
                object obj = ResourceManager.GetObject("MainFormHelp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove {0}?.
        /// </summary>
        internal static string MainFormOperationRemovePrompt {
            get {
                return ResourceManager.GetString("MainFormOperationRemovePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Operation Confirmation.
        /// </summary>
        internal static string MainFormOperationRemoveTitle {
            get {
                return ResourceManager.GetString("MainFormOperationRemoveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This project has not been saved. Do you want to save?.
        /// </summary>
        internal static string MainFormProjectOpenSavePrompt {
            get {
                return ResourceManager.GetString("MainFormProjectOpenSavePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project save failed: {0}.
        /// </summary>
        internal static string MainFormProjectSaveFailed {
            get {
                return ResourceManager.GetString("MainFormProjectSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Project.
        /// </summary>
        internal static string MainFormProjectSaveMessage {
            get {
                return ResourceManager.GetString("MainFormProjectSaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project saved successfully.
        /// </summary>
        internal static string MainFormProjectSaveSucceeded {
            get {
                return ResourceManager.GetString("MainFormProjectSaveSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected project no longer exists. Do you want to remove it from the recent project list?.
        /// </summary>
        internal static string MainFormRecentProjectRemovePrompt {
            get {
                return ResourceManager.GetString("MainFormRecentProjectRemovePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Project Confirmation.
        /// </summary>
        internal static string MainFormRecentProjectRemoveTitle {
            get {
                return ResourceManager.GetString("MainFormRecentProjectRemoveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MainFormSaveProject {
            get {
                object obj = ResourceManager.GetObject("MainFormSaveProject", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MainFormSaveProjectAs {
            get {
                object obj = ResourceManager.GetObject("MainFormSaveProjectAs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MainFormStop {
            get {
                object obj = ResourceManager.GetObject("MainFormStop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MainFormWindows {
            get {
                object obj = ResourceManager.GetObject("MainFormWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap New_Step {
            get {
                object obj = ResourceManager.GetObject("New_Step", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors ({0}).
        /// </summary>
        internal static string NotificationFormErrorsText {
            get {
                return ResourceManager.GetString("NotificationFormErrorsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages ({0}).
        /// </summary>
        internal static string NotificationFormMessagesText {
            get {
                return ResourceManager.GetString("NotificationFormMessagesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnings ({0}).
        /// </summary>
        internal static string NotificationFormWarningsText {
            get {
                return ResourceManager.GetString("NotificationFormWarningsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon NotificationsForm16 {
            get {
                object obj = ResourceManager.GetObject("NotificationsForm16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NotificationsForm24 {
            get {
                object obj = ResourceManager.GetObject("NotificationsForm24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NotificationsFormClearLogs {
            get {
                object obj = ResourceManager.GetObject("NotificationsFormClearLogs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NotificationsFormError {
            get {
                object obj = ResourceManager.GetObject("NotificationsFormError", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NotificationsFormOpenLogFolder {
            get {
                object obj = ResourceManager.GetObject("NotificationsFormOpenLogFolder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NotificationsFormViewErrorLog {
            get {
                object obj = ResourceManager.GetObject("NotificationsFormViewErrorLog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NotificationsFormViewNotificationLog {
            get {
                object obj = ResourceManager.GetObject("NotificationsFormViewNotificationLog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NotificationsFormWarning {
            get {
                object obj = ResourceManager.GetObject("NotificationsFormWarning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OpenProject {
            get {
                object obj = ResourceManager.GetObject("OpenProject", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pause {
            get {
                object obj = ResourceManager.GetObject("Pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon PerformanceForm16 {
            get {
                object obj = ResourceManager.GetObject("PerformanceForm16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PerformanceForm24 {
            get {
                object obj = ResourceManager.GetObject("PerformanceForm24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Progress {
            get {
                object obj = ResourceManager.GetObject("Progress", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ProgressForm16 {
            get {
                object obj = ResourceManager.GetObject("ProgressForm16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ProgressForm24 {
            get {
                object obj = ResourceManager.GetObject("ProgressForm24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project close failed: {0}.
        /// </summary>
        internal static string ProjectCloseFailed {
            get {
                return ResourceManager.GetString("ProjectCloseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create a new project: {0}.
        /// </summary>
        internal static string ProjectCreateFailed {
            get {
                return ResourceManager.GetString("ProjectCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project created successfully.
        /// </summary>
        internal static string ProjectCreateSucceeded {
            get {
                return ResourceManager.GetString("ProjectCreateSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project files|*{0}.
        /// </summary>
        internal static string ProjectFileFilter {
            get {
                return ResourceManager.GetString("ProjectFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ProjectFormBatch {
            get {
                object obj = ResourceManager.GetObject("ProjectFormBatch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected project is already open..
        /// </summary>
        internal static string ProjectOpenAlreadyText {
            get {
                return ResourceManager.GetString("ProjectOpenAlreadyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Already Open.
        /// </summary>
        internal static string ProjectOpenAlreadyTitle {
            get {
                return ResourceManager.GetString("ProjectOpenAlreadyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project load failed: {0}.
        /// </summary>
        internal static string ProjectOpenFailed {
            get {
                return ResourceManager.GetString("ProjectOpenFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This project has not been saved. Do you want to save?.
        /// </summary>
        internal static string ProjectOpenSavePrompt {
            get {
                return ResourceManager.GetString("ProjectOpenSavePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project loaded successfully.
        /// </summary>
        internal static string ProjectOpenSucceeded {
            get {
                return ResourceManager.GetString("ProjectOpenSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Properties16 {
            get {
                object obj = ResourceManager.GetObject("Properties16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Properties24 {
            get {
                object obj = ResourceManager.GetObject("Properties24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Properties32 {
            get {
                object obj = ResourceManager.GetObject("Properties32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RecentProjects {
            get {
                object obj = ResourceManager.GetObject("RecentProjects", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RemoveDataSouce {
            get {
                object obj = ResourceManager.GetObject("RemoveDataSouce", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RemoveRecentProject {
            get {
                object obj = ResourceManager.GetObject("RemoveRecentProject", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RowCount {
            get {
                object obj = ResourceManager.GetObject("RowCount", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon SampleDataViewer16 {
            get {
                object obj = ResourceManager.GetObject("SampleDataViewer16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Surgeon {
            get {
                object obj = ResourceManager.GetObject("Surgeon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Trash {
            get {
                object obj = ResourceManager.GetObject("Trash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap View {
            get {
                object obj = ResourceManager.GetObject("View", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open window: {0}.
        /// </summary>
        internal static string WindowOpenFailed {
            get {
                return ResourceManager.GetString("WindowOpenFailed", resourceCulture);
            }
        }
    }
}
